### ISSUE TITLE
403 forbidden error when accessing yii2-start

### ISSUE THREAD

**Issue by rajesh188** [vova07/yii2-start#124]
i followed step by step instructions mentioned in readme.md,except configuring virtual hosts which i do not understand.so when accessing localhost/yii2-start i get 403 forbidden error

**Comment by vova07** [comment]
Hi @rajesh188 ,
I'm not sure about `wamp` but i guess you'll need to create a VH, or at least to allow `override` his config from `.htaccess`. I think you get 403 error right because you don't have  `AllowOverride All` in your `wamp` config.
If you have a problems with VH please take a look on [this tutorial](http://www.kristengrote.com/blog/articles/how-to-set-up-virtual-hosts-using-wamp) or just google something else for `wamp virtual host configuration`.
Let me know if you'll have other questions.

**Comment by rajesh188** [comment]
can i use yii2-start without virtual hosts configuration as any other project from localhost

**Comment by vova07** [comment]
Only if you'll use `localhost` directory like a `yii2-start` root.
